### ISSUE TITLE
Last commit makes impossible to download vspk

### ISSUE THREAD

**Issue by maesoser** [nuagenetworks/vspk-go#8]
Last commit makes impossible to even download the library due to the reference of a non-existing object "UBR" on [nsgateway.go](https://github.com/nuagenetworks/vspk-go/commit/47527dfbf66c21582abc38fe7902e96cde4e44ed#diff-1d51a513db93da463dcec62fdc825e39):
 
![{E7AD3A0B-3DF5-46F3-8DC2-72B4A2216768}](https://user-images.githubusercontent.com/2486253/55887124-41a03900-5bad-11e9-959c-4297e14ef348.png)

This is the definition of the variable `Functions`:

```go
type NSGateway struct {
        // ... //
	Functions                            []interface{} `json:"functions,omitempty"`
        // ... //
}
```

Function `NewNSGateway` is initializing such variable with an non-existing object:

```go
// NewNSGateway returns a new *NSGateway
func NewNSGateway() *NSGateway {
		ConfigurationStatus:              "UNKNOWN",
		ControlTrafficCOSValue:           7,
		ControlTrafficDSCPValue:          56,
		Functions:                        UBR,
                // ... //
```

`Functions` variable seems to be a list according to the [API Reference](https://nuagenetworks.github.io/vsd-api-documentation/v5_0/nsgateway.html#attr_functions)

**Comment by maesoser** [comment]
Hi,

¿Did you find the root cause? As workaround I've removed the line `Functions:    UBR,` on `NewNSGateway()` function.

BR

**Comment by pdellaert** [comment]
Hi @maesoser,

We've identified the issue, and i'm working on a fix, but i want to combine it with a few others. In the meantime, i'll update it specifically here manually, while i plan for the actual long term fix.

**Comment by hellt** [comment]
@pdellaert as I see vspk-go stopped to be autogenerated since 5.3.1
I have no problems go-getting the 5.3.1, but I wonder if we have problems with generating 5.4.1 package?

**Comment by hellt** [comment]
ah, I see, you changed the naming scheme `vM.m.p` is now `rM.m.p`. Now I need to figure out how `go.mod` fetches the version during the package import, since clearly it has some issues with that

`cat go.mod`:
```
module github.com/hellt/x-vspk-go

go 1.12

require (
	github.com/ccding/go-config-reader v0.0.0-20130817225950-8b6c2b50197f // indirect
	github.com/ccding/go-logging v0.0.0-20170420173934-e6419c8d4d49 // indirect
	github.com/kardianos/osext v0.0.0-20190222173326-2bc1f35cddc0 // indirect
	github.com/nuagenetworks/go-bambou v1.0.1
	github.com/nuagenetworks/vspk-go v5.3.1+incompatible
	github.com/sirupsen/logrus v1.4.2 // indirect
)
```

the `v5.3.1+incompatible` is highly suspicious, I think `go mod` has problems with fetching rX.Y.Z tags

**ADD**
Ok, the problem is indeed with `r-tagged` releases, the `go mod` import mechanism will not treat this tag as a release tag, since [they require it to be in the `v(major).(minor).(patch)` form](https://github.com/golang/go/wiki/Modules#modules). Since with go 1.13 `go mod` will be a default versioning engine, we should rename the tags I think

**Comment by pdellaert** [comment]
@hellt, i solved that problem... the v* tags are still added manually. Sorry.

I've added v5.3.2, v5.3.3, v5.4.1

**Comment by pdellaert** [comment]
I think this has been all resolved now? If not, feel free to let me know what else is missing for this ticket..
